### ISSUE TITLE
Deployment of the serverless IIIF application in the eu-west-1 region fails

### ISSUE THREAD

**Issue by fcadili** [nulib/serverless-iiif#1]
I tried to deploy the serverless IIIF application using https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/create/template?templateURL=https://nul-public.s3.amazonaws.com/serverless-iiif/deploy.yaml. 
The process terminate with a rollback with a CREATE_FAILED error related to Dependencies50202cd119. The explaination of the error was:
> Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a4f0d97a-3e93-42e5-8a84-f9e717469023).

I retry the deployment in the us-east-1 region and the deploy procedure works fine.

**Comment by mbklein** [comment]
Hmm. Yes, the bucket with the Lambda function code is in `us-east-1`, which ties the deployment to `us-east-1`. I can look into some solutions, but relocating the code, customizing the template, and then redeploying using the custom template might be the best you can do for now.

**Comment by jgondron** [comment]
Once #2 is merged, you should be able to just rebuild, package, and deploy with something like:

```
cd dependencies/nodejs
npm install
cd ../..

aws cloudformation package \
  --template-file ./template.yml \
  --s3-bucket my-package-bucket \
  --region eu-west-1 \
  --output-template-file package_output.yml

aws cloudformation deploy \
  --region eu-west-1 \
  --template-file ./package_output.yml \
  --stack-name serverless-iiif \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides SourceBucket=my-image-source-bucket
```
Note: you'll need node 10 to rebuild the dependencies. 12 seems to be broken (I'll add an issue on this)

**Comment by edsilv** [comment]
Deploying using [SAM](https://aws.amazon.com/serverless/sam/)

Windows key + “Ubuntu” to run [Ubuntu on WSL](https://www.microsoft.com/store/productId/9NBLGGH4MSV6).
Clone and cd to serverless-iiif repo.

```
nvm use 10.19.0
cd dependencies/nodejs
npm i
cd ../../
sam deploy --guided
Stack Name [sam-app]: name-your-stack
AWS Region [us-east-1]: your-region
Parameter SourceBucket []: image-bucket-name
Parameter StageName [latest]:
Confirm changes before deploy [y/N]: n
Allow SAM CLI IAM role creation [Y/n]: y
Save arguments to samconfig.toml [Y/n]: y
```

**Comment by tpendragon** [comment]
SAM worked for me, but `npm install` has to be done in a linux environment. I did the following on a mac:

`docker run -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm install`
