### ISSUE TITLE
NodeJS 8.10 no longer supported

### ISSUE THREAD

**Issue by tpendragon** [nulib/serverless-iiif#6]
In trying to deploy this I get the following:

> The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 39b92f82-90fe-49e6-b394-4ae9fa59fde3)

**Comment by mbklein** [comment]
Fixed in the template
